_include: https://gitea.msqu.de/devops/build_scripts/raw/branch/main/drone/ContainerImageDocker.yml

kind: pipeline
name: default

steps:

  - <<: *ContainerImageDocker
    name: cloudns
    environment:
      CONTEXT_DIR: cloudns
      DOCKERFILE: cloudns/Dockerfile
      DOCKER_MULTI_ARCH: "true"
      TAG_EXPLICIT: "cloudns"
      TAG_REF_NORMALIZED_ENABLE: "false"
      ADDITIONAL_REGISTRIES: "schmitzis/monorepo:dns-"
      REGISTRY_AUTH_JSON:
        from_secret: DOCKER_HUB_AUTH_SCHMITZIS

  - <<: *ContainerImageDocker
    name: cloudns-shot
    environment:
      CONTEXT_DIR: cloudns-shot
      DOCKERFILE: cloudns-shot/Dockerfile
      DOCKER_MULTI_ARCH: "true"
      TAG_EXPLICIT: "cloudns-shot"
      TAG_REF_NORMALIZED_ENABLE: "false"
      ADDITIONAL_REGISTRIES: "schmitzis/monorepo:dns-"
      REGISTRY_AUTH_JSON:
        from_secret: DOCKER_HUB_AUTH_SCHMITZIS

  - <<: *ContainerImageDocker
    name: curl
    environment:
      CONTEXT_DIR: curl
      DOCKERFILE: curl/Dockerfile
      DOCKER_MULTI_ARCH: "true"
      TAG_EXPLICIT: "curl"
      TAG_REF_NORMALIZED_ENABLE: "false"
      ADDITIONAL_REGISTRIES: "schmitzis/monorepo:dns-"
      REGISTRY_AUTH_JSON:
        from_secret: DOCKER_HUB_AUTH_SCHMITZIS

  - <<: *ContainerImageDocker
    name: digitalocean
    environment:
      CONTEXT_DIR: digitalocean
      DOCKERFILE: digitalocean/Dockerfile
      DOCKER_MULTI_ARCH: "true"
      TAG_EXPLICIT: "digitalocean"
      TAG_REF_NORMALIZED_ENABLE: "false"
      ADDITIONAL_REGISTRIES: "schmitzis/monorepo:dns-"
      REGISTRY_AUTH_JSON:
        from_secret: DOCKER_HUB_AUTH_SCHMITZIS

  - <<: *ContainerImageDocker
    name: digitalocean-shot
    environment:
      CONTEXT_DIR: digitalocean-shot
      DOCKERFILE: digitalocean-shot/Dockerfile
      DOCKER_MULTI_ARCH: "true"
      TAG_EXPLICIT: "digitalocean-shot"
      TAG_REF_NORMALIZED_ENABLE: "false"
      ADDITIONAL_REGISTRIES: "schmitzis/monorepo:dns-"
      REGISTRY_AUTH_JSON:
        from_secret: DOCKER_HUB_AUTH_SCHMITZIS

  - <<: *ContainerImageDocker
    name: desec
    environment:
      CONTEXT_DIR: desec
      DOCKERFILE: desec/Dockerfile
      DOCKER_MULTI_ARCH: "true"
      TAG_EXPLICIT: "desec"
      TAG_REF_NORMALIZED_ENABLE: "false"
      ADDITIONAL_REGISTRIES: "schmitzis/monorepo:dns-"
      REGISTRY_AUTH_JSON:
        from_secret: DOCKER_HUB_AUTH_SCHMITZIS

  - <<: *ContainerImageDocker
    name: hetzner
    environment:
      CONTEXT_DIR: hetzner
      DOCKERFILE: hetzner/Dockerfile
      DOCKER_MULTI_ARCH: "true"
      TAG_EXPLICIT: "hetzner"
      TAG_REF_NORMALIZED_ENABLE: "false"
      ADDITIONAL_REGISTRIES: "schmitzis/monorepo:dns-"
      REGISTRY_AUTH_JSON:
        from_secret: DOCKER_HUB_AUTH_SCHMITZIS

  - <<: *ContainerImageDocker
    name: hurricane electric
    environment:
      CONTEXT_DIR: he
      DOCKERFILE: he/Dockerfile
      DOCKER_MULTI_ARCH: "true"
      TAG_EXPLICIT: "he"
      TAG_REF_NORMALIZED_ENABLE: "false"
      ADDITIONAL_REGISTRIES: "schmitzis/monorepo:dns-"
      REGISTRY_AUTH_JSON:
        from_secret: DOCKER_HUB_AUTH_SCHMITZIS

  - <<: *ContainerImageDocker
    name: netcup
    environment:
      CONTEXT_DIR: netcup
      DOCKERFILE: netcup/Dockerfile
      DOCKER_MULTI_ARCH: "true"
      TAG_EXPLICIT: "netcup"
      TAG_REF_NORMALIZED_ENABLE: "false"
      ADDITIONAL_REGISTRIES: "schmitzis/monorepo:dns-"
      REGISTRY_AUTH_JSON:
        from_secret: DOCKER_HUB_AUTH_SCHMITZIS

services:
- <<: *ContainerImageDockerDinDService
  name: svc_docker_dind

volumes:
- <<: *ContainerImageDockerVolume
