_include: https://gitea.msqu.de/devops/build_scripts/raw/branch/main/drone/ContainerImageDocker.yml

kind: pipeline
name: default

steps:

  - <<: *ContainerImageDocker
    name: cloudns
    depends_on: [ clone ]
    environment:
      CONTEXT_DIR: cloudns
      DOCKERFILE: cloudns/Dockerfile
      TAG_EXPLICIT: "cloudns"
      TAG_REF_NORMALIZED_ENABLE: "false"

  - <<: *ContainerImageDocker
    name: cloudns-shot
    depends_on: [ clone ]
    environment:
      CONTEXT_DIR: cloudns-shot
      DOCKERFILE: cloudns-shot/Dockerfile
      TAG_EXPLICIT: "cloudns-shot"
      TAG_REF_NORMALIZED_ENABLE: "false"

  - <<: *ContainerImageDocker
    name: curl
    depends_on: [ clone ]
    environment:
      CONTEXT_DIR: curl
      DOCKERFILE: curl/Dockerfile
      TAG_EXPLICIT: "curl"
      TAG_REF_NORMALIZED_ENABLE: "false"

  - <<: *ContainerImageDocker
    name: digitalocean
    depends_on: [ clone ]
    environment:
      CONTEXT_DIR: digitalocean
      DOCKERFILE: digitalocean/Dockerfile
      TAG_EXPLICIT: "digitalocean"
      TAG_REF_NORMALIZED_ENABLE: "false"

  - <<: *ContainerImageDocker
    name: digitalocean-shot
    depends_on: [ clone ]
    environment:
      CONTEXT_DIR: digitalocean-shot
      DOCKERFILE: digitalocean-shot/Dockerfile
      TAG_EXPLICIT: "digitalocean-shot"
      TAG_REF_NORMALIZED_ENABLE: "false"

  - <<: *ContainerImageDocker
    name: hetzner
    depends_on: [ clone ]
    environment:
      CONTEXT_DIR: hetzner
      DOCKERFILE: hetzner/Dockerfile
      TAG_EXPLICIT: "hetzner"
      TAG_REF_NORMALIZED_ENABLE: "false"

  - <<: *ContainerImageDocker
    name: netcup
    depends_on: [ clone ]
    environment:
      CONTEXT_DIR: netcup
      DOCKERFILE: netcup/Dockerfile
      TAG_EXPLICIT: "netcup"
      TAG_REF_NORMALIZED_ENABLE: "false"

services:
- <<: *ContainerImageDockerDinDService
  name: svc_docker_dind

volumes:
- <<: *ContainerImageDockerVolume
