image: docker:stable

services:
- name: docker:dind
  command: ["--experimental"]

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_DRIVER: overlay2

before_script:
  # Enable experimental features in Docker client
  - mkdir $HOME/.docker
  - "echo -e '{\n  \"experimental\": \"enabled\"\n}' | tee $HOME/.docker/config.json"
  # login to gitlab ci
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

.build-template: &build-template
  stage: build
  script:
    - >
      docker build \
        --squash \
        --no-cache \
        --tag $CONTAINER_IMAGE:$IMAGE_TAG-$CI_COMMIT_SHA \
        --tag $CONTAINER_IMAGE:$IMAGE_TAG \
        -f ${DOCKERFILE:-./Dockerfile} \
        .
    - docker push $CONTAINER_IMAGE:$IMAGE_TAG
    # add tag if available
    - >
      if [[ ! -z $CI_BUILD_REF_NAME ]]; then
        docker tag $CONTAINER_IMAGE:$IMAGE_TAG-$CI_COMMIT_SHA \
                   $CONTAINER_IMAGE:$IMAGE_TAG-$CI_BUILD_REF_NAME
        docker push $CONTAINER_IMAGE:$IMAGE_TAG-$CI_BUILD_REF_NAME
      fi

cloudns:
  <<: *build-template
  variables:
    IMAGE_TAG: "cloudns"
    DOCKERFILE: "cloudns/Dockerfile"

cloudns-shot:
  <<: *build-template
  variables:
    IMAGE_TAG: "cloudns-shot"
    DOCKERFILE: "cloudns-shot/Dockerfile"
