---
image:
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]

variables:
  CI_REGISTRY: registry.msqu.de
  CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_NAME

.build-template: &build-template
  stage: build
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"},\"$DOCKER_REGISTRY\":{\"auth\":\"$(echo -n ${DOCKER_USERNAME}:${DOCKER_PASSWORD} | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

    # default tag based on commit
    - IMAGE_DESTS="--destination $CONTAINER_IMAGE:${IMAGE_TAG}"
    - IMAGE_DESTS="$IMAGE_DESTS --destination $DOCKER_USERNAME/${CI_PROJECT_NAME}:${IMAGE_TAG}"

    # add tag for reference if available
    - |
      if [[ ! -z $CI_COMMIT_REF_NAME ]]; then
        # replace / with - in reference names
        REF_TAG_NORMALIZED=$(echo $CI_COMMIT_REF_NAME | sed s:/:-:g)
        IMAGE_DESTS="$IMAGE_DESTS --destination $DOCKER_USERNAME/${CI_PROJECT_NAME}:${IMAGE_TAG}-$REF_TAG_NORMALIZED"
        IMAGE_DESTS="$IMAGE_DESTS --destination $CONTAINER_IMAGE:${IMAGE_TAG}-$REF_TAG_NORMALIZED"
      fi

    - >
      /kaniko/executor \
        --context "${CI_PROJECT_DIR}" \
        --log-timestamp=true \
        --push-retry=2 \
        --single-snapshot \
        --use-new-run \
        --dockerfile ${DOCKERFILE:-./Dockerfile} \
        $IMAGE_DESTS

cloudns:
  <<: *build-template
  variables:
    IMAGE_TAG: "cloudns"

cloudns-shot:
  <<: *build-template
  variables:
    IMAGE_TAG: "cloudns-shot"

curl:
  <<: *build-template
  variables:
    IMAGE_TAG: "curl"

digitalocean:
  <<: *build-template
  variables:
    IMAGE_TAG: "digitalocean"

digitalocean-shot:
  <<: *build-template
  variables:
    IMAGE_TAG: "digitalocean-shot"

hetzner:
  <<: *build-template
  variables:
    IMAGE_TAG: "hetzner"

netcup:
  <<: *build-template
  variables:
    IMAGE_TAG: "netcup"