---
name: Docker Image
on:
  issue_comment:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@master

      # - id: information
      #   uses: https://gitea.dhswt.de/actions/information@master

      - name: Set up QEMU
        uses: https://github.com/docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3

      - name: Build and push Docker image cloudns
        uses: https://gitea.msqu.de/cicd/docker@master
        #uses: https://gitea.dhswt.de/actions/docker@master
        with:
          docker_context_dir: ${{ github.workspace }}/cloudns
          dockerfile: ${{ github.workspace }}/cloudns/Dockerfile
          docker_args: "--tag gitea.msqu.de/devops/dns:cloudns"
          tag_commit_enable: false
          tag_semver_enable: false
          tag_ref_normalized_enable: false
          additional_registries: "schmitzis/monorepo:cloudns"
          registry_auth_json: ${{ secrets.DOCKER_HUB_AUTH_SCHMITZIS }}
          docker_multiarch: true
          ci_registry_password: ${{ secrets.ACT_RUNNER_PAT }}

      - name: Build and push Docker image cloudns-shot
        if: success() || failure()
        uses: https://gitea.msqu.de/cicd/docker@master
        #uses: https://gitea.dhswt.de/actions/docker@master
        with:
          docker_context_dir: ${{ github.workspace }}/cloudns-shot
          dockerfile: ${{ github.workspace }}/cloudns-shot/Dockerfile
          docker_args: "--tag gitea.msqu.de/devops/dns:cloudns-shot"
          tag_commit_enable: false
          tag_semver_enable: false
          tag_ref_normalized_enable: false
          additional_registries: "schmitzis/monorepo:cloudns-shot"
          registry_auth_json: ${{ secrets.DOCKER_HUB_AUTH_SCHMITZIS }}
          docker_multiarch: true
          ci_registry_password: ${{ secrets.ACT_RUNNER_PAT }}

      - name: Build and push Docker image curl
        if: success() || failure()
        uses: https://gitea.msqu.de/cicd/docker@master
        #uses: https://gitea.dhswt.de/actions/docker@master
        with:
          docker_context_dir: ${{ github.workspace }}/curl
          dockerfile: ${{ github.workspace }}/curl/Dockerfile
          docker_args: "--tag gitea.msqu.de/devops/dns:curl"
          tag_commit_enable: false
          tag_semver_enable: false
          tag_ref_normalized_enable: false
          additional_registries: "schmitzis/monorepo:curl"
          registry_auth_json: ${{ secrets.DOCKER_HUB_AUTH_SCHMITZIS }}
          docker_multiarch: true
          ci_registry_password: ${{ secrets.ACT_RUNNER_PAT }}

      - name: Build and push Docker image digitalocean
        if: success() || failure()
        uses: https://gitea.msqu.de/cicd/docker@master
        #uses: https://gitea.dhswt.de/actions/docker@master
        with:
          docker_context_dir: ${{ github.workspace }}/digitalocean
          dockerfile: ${{ github.workspace }}/digitalocean/Dockerfile
          docker_args: "--tag gitea.msqu.de/devops/dns:cloudns"
          tag_commit_enable: false
          tag_semver_enable: false
          tag_ref_normalized_enable: false
          additional_registries: "schmitzis/monorepo:digitalocean"
          registry_auth_json: ${{ secrets.DOCKER_HUB_AUTH_SCHMITZIS }}
          docker_multiarch: true
          ci_registry_password: ${{ secrets.ACT_RUNNER_PAT }}

      - name: Build and push Docker image digitalocean-shot
        if: success() || failure()
        uses: https://gitea.msqu.de/cicd/docker@master
        #uses: https://gitea.dhswt.de/actions/docker@master
        with:
          docker_context_dir: ${{ github.workspace }}/digitalocean-shot
          dockerfile: ${{ github.workspace }}/digitalocean-shot/Dockerfile
          docker_args: "--tag gitea.msqu.de/devops/dns:digitalocean-shot"
          tag_commit_enable: false
          tag_semver_enable: false
          tag_ref_normalized_enable: false
          additional_registries: "schmitzis/monorepo:digitalocean-shot"
          registry_auth_json: ${{ secrets.DOCKER_HUB_AUTH_SCHMITZIS }}
          docker_multiarch: true
          ci_registry_password: ${{ secrets.ACT_RUNNER_PAT }}

      - name: Build and push Docker image desec
        if: success() || failure()
        uses: https://gitea.msqu.de/cicd/docker@master
        #uses: https://gitea.dhswt.de/actions/docker@master
        with:
          docker_context_dir: ${{ github.workspace }}/desec
          dockerfile: ${{ github.workspace }}/desec/Dockerfile
          docker_args: "--tag gitea.msqu.de/devops/dns:desec"
          tag_commit_enable: false
          tag_semver_enable: false
          tag_ref_normalized_enable: false
          additional_registries: "schmitzis/monorepo:desec"
          registry_auth_json: ${{ secrets.DOCKER_HUB_AUTH_SCHMITZIS }}
          docker_multiarch: true
          ci_registry_password: ${{ secrets.ACT_RUNNER_PAT }}

      - name: Build and push Docker image hetzner
        if: success() || failure()
        uses: https://gitea.msqu.de/cicd/docker@master
        #uses: https://gitea.dhswt.de/actions/docker@master
        with:
          docker_context_dir: ${{ github.workspace }}/hetzner
          dockerfile: ${{ github.workspace }}/hetzner/Dockerfile
          docker_args: "--tag gitea.msqu.de/devops/dns:hetzner"
          tag_commit_enable: false
          tag_semver_enable: false
          tag_ref_normalized_enable: false
          additional_registries: "schmitzis/monorepo:hetzner"
          registry_auth_json: ${{ secrets.DOCKER_HUB_AUTH_SCHMITZIS }}
          docker_multiarch: true
          ci_registry_password: ${{ secrets.ACT_RUNNER_PAT }}

      - name: Build and push Docker image hurricane electric
        if: success() || failure()
        uses: https://gitea.msqu.de/cicd/docker@master
        #uses: https://gitea.dhswt.de/actions/docker@master
        with:
          docker_context_dir: ${{ github.workspace }}/he
          dockerfile: ${{ github.workspace }}/he/Dockerfile
          docker_args: "--tag gitea.msqu.de/devops/dns:he"
          tag_commit_enable: false
          tag_semver_enable: false
          tag_ref_normalized_enable: false
          additional_registries: "schmitzis/monorepo:digitalocean"
          registry_auth_json: ${{ secrets.DOCKER_HUB_AUTH_SCHMITZIS }}
          docker_multiarch: true
          ci_registry_password: ${{ secrets.ACT_RUNNER_PAT }}

      - name: Build and push Docker image netcup
        if: success() || failure()
        uses: https://gitea.msqu.de/cicd/docker@master
        #uses: https://gitea.dhswt.de/actions/docker@master
        with:
          docker_context_dir: ${{ github.workspace }}/netcup
          dockerfile: ${{ github.workspace }}/netcup/Dockerfile
          docker_args: "--tag gitea.msqu.de/devops/dns:netcup"
          tag_commit_enable: false
          tag_semver_enable: false
          tag_ref_normalized_enable: false
          additional_registries: "schmitzis/monorepo:netcup"
          registry_auth_json: ${{ secrets.DOCKER_HUB_AUTH_SCHMITZIS }}
          docker_multiarch: true
          ci_registry_password: ${{ secrets.ACT_RUNNER_PAT }}
