---
name: Docker Image
on:
  issue_comment:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@master

      # - id: information
      #   uses: https://gitea.dhswt.de/actions/information@master

      - name: Set up QEMU
        uses: https://github.com/docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3

      - name: Build and push Docker image cloudns
        uses: https://gitea.msqu.de/cicd/docker@master
        #uses: https://gitea.dhswt.de/actions/docker@master
        with:
          docker_context_dir: ${{ github.workspace }}/cloudns
          dockerfile: ${{ github.workspace }}/cloudns/Dockerfile
          docker_args: "--tag gitea.msqu.de/devops/dns:cloudns"
          tag_semver_enable: false
          additional_registries: "schmitzis/monorepo:cloudns"
          registry_auth_json: ${{ secrets.DOCKER_HUB_AUTH_SCHMITZIS }}
          docker_multiarch: true
          ci_registry_password: ${{ secrets.ACT_RUNNER_PAT }}
