---
name: Docker Image
on:
  issue_comment:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@master

      # - id: information
      #   uses: https://gitea.dhswt.de/actions/information@master

      - name: Set up QEMU
        uses: https://github.com/docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3

      - name: Build and push Docker image cloudns
        uses: https://gitea.msqu.de/cicd/docker@master
        #uses: https://gitea.dhswt.de/actions/docker@master
        with:
          docker_context_dir: ${{ github.workspace }}/cloudns
          dockerfile: ${{ github.workspace }}/cloudns/Dockerfile
          additional_registries: "schmitzis/dns"
          tags_additional: cloudns
          tag_commit_enable: false
          tag_semver_enable: false
          tag_ref_normalized_enable: false
          registry_auth_json: ${{ secrets.DOCKER_HUB_AUTH_SCHMITZIS }}
          docker_multiarch: true
          ci_registry_password: ${{ secrets.ACT_RUNNER_PAT }}

      - name: Build and push Docker image cloudns-shot
        if: success() || failure()
        uses: https://gitea.msqu.de/cicd/docker@master
        #uses: https://gitea.dhswt.de/actions/docker@master
        with:
          docker_context_dir: ${{ github.workspace }}/cloudns-shot
          dockerfile: ${{ github.workspace }}/cloudns-shot/Dockerfile
          additional_registries: "schmitzis/dns"
          tags_additional: cloudns-shot
          tag_commit_enable: false
          tag_semver_enable: false
          tag_ref_normalized_enable: false
          registry_auth_json: ${{ secrets.DOCKER_HUB_AUTH_SCHMITZIS }}
          docker_multiarch: true
          ci_registry_password: ${{ secrets.ACT_RUNNER_PAT }}

      - name: Build and push Docker image curl
        if: success() || failure()
        uses: https://gitea.msqu.de/cicd/docker@master
        #uses: https://gitea.dhswt.de/actions/docker@master
        with:
          docker_context_dir: ${{ github.workspace }}/curl
          dockerfile: ${{ github.workspace }}/curl/Dockerfile
          additional_registries: "schmitzis/dns"
          tags_additional: curl
          tag_commit_enable: false
          tag_semver_enable: false
          tag_ref_normalized_enable: false
          registry_auth_json: ${{ secrets.DOCKER_HUB_AUTH_SCHMITZIS }}
          docker_multiarch: true
          ci_registry_password: ${{ secrets.ACT_RUNNER_PAT }}

      - name: Build and push Docker image digitalocean
        if: success() || failure()
        uses: https://gitea.msqu.de/cicd/docker@master
        #uses: https://gitea.dhswt.de/actions/docker@master
        with:
          docker_context_dir: ${{ github.workspace }}/digitalocean
          dockerfile: ${{ github.workspace }}/digitalocean/Dockerfile
          additional_registries: "schmitzis/dns"
          tags_additional: digitalocean
          tag_commit_enable: false
          tag_semver_enable: false
          tag_ref_normalized_enable: false
          registry_auth_json: ${{ secrets.DOCKER_HUB_AUTH_SCHMITZIS }}
          docker_multiarch: true
          ci_registry_password: ${{ secrets.ACT_RUNNER_PAT }}

      - name: Build and push Docker image digitalocean-shot
        if: success() || failure()
        uses: https://gitea.msqu.de/cicd/docker@master
        #uses: https://gitea.dhswt.de/actions/docker@master
        with:
          docker_context_dir: ${{ github.workspace }}/digitalocean-shot
          dockerfile: ${{ github.workspace }}/digitalocean-shot/Dockerfile
          additional_registries: "schmitzis/dns"
          tags_additional: digitalocean-shot
          tag_commit_enable: false
          tag_semver_enable: false
          tag_ref_normalized_enable: false
          registry_auth_json: ${{ secrets.DOCKER_HUB_AUTH_SCHMITZIS }}
          docker_multiarch: true
          ci_registry_password: ${{ secrets.ACT_RUNNER_PAT }}

      - name: Build and push Docker image desec
        if: success() || failure()
        uses: https://gitea.msqu.de/cicd/docker@master
        #uses: https://gitea.dhswt.de/actions/docker@master
        with:
          docker_context_dir: ${{ github.workspace }}/desec
          dockerfile: ${{ github.workspace }}/desec/Dockerfile
          additional_registries: "schmitzis/dns"
          tags_additional: desec
          tag_commit_enable: false
          tag_semver_enable: false
          tag_ref_normalized_enable: false
          registry_auth_json: ${{ secrets.DOCKER_HUB_AUTH_SCHMITZIS }}
          docker_multiarch: true
          ci_registry_password: ${{ secrets.ACT_RUNNER_PAT }}

      - name: Build and push Docker image hetzner
        if: success() || failure()
        uses: https://gitea.msqu.de/cicd/docker@master
        #uses: https://gitea.dhswt.de/actions/docker@master
        with:
          docker_context_dir: ${{ github.workspace }}/hetzner
          dockerfile: ${{ github.workspace }}/hetzner/Dockerfile
          additional_registries: "schmitzis/dns"
          tags_additional: hetzner
          tag_commit_enable: false
          tag_semver_enable: false
          tag_ref_normalized_enable: false
          registry_auth_json: ${{ secrets.DOCKER_HUB_AUTH_SCHMITZIS }}
          docker_multiarch: true
          ci_registry_password: ${{ secrets.ACT_RUNNER_PAT }}

      - name: Build and push Docker image hurricane electric
        if: success() || failure()
        uses: https://gitea.msqu.de/cicd/docker@master
        #uses: https://gitea.dhswt.de/actions/docker@master
        with:
          docker_context_dir: ${{ github.workspace }}/he
          dockerfile: ${{ github.workspace }}/he/Dockerfile
          additional_registries: "schmitzis/dns"
          tags_additional: he
          tag_commit_enable: false
          tag_semver_enable: false
          tag_ref_normalized_enable: false
          registry_auth_json: ${{ secrets.DOCKER_HUB_AUTH_SCHMITZIS }}
          docker_multiarch: true
          ci_registry_password: ${{ secrets.ACT_RUNNER_PAT }}

      - name: Build and push Docker image netcup
        if: success() || failure()
        #uses: https://gitea.msqu.de/cicd/docker@master
        uses: https://gitea.dhswt.de/actions/docker@master
        with:
          docker_context_dir: ${{ github.workspace }}/netcup
          dockerfile: ${{ github.workspace }}/netcup/Dockerfile
          additional_registries: "schmitzis/dns"
          tags_additional: netcup
          tag_commit_enable: false
          tag_semver_enable: false
          tag_ref_normalized_enable: false
          registry_auth_json: ${{ secrets.DOCKER_HUB_AUTH_SCHMITZIS }}
          docker_multiarch: true
          ci_registry_password: ${{ secrets.ACT_RUNNER_PAT }}
